### ISSUE TITLE
Warning: convertedHtml.html is not a function (with inky 1.3.6)

### ISSUE THREAD

**Issue by alekart** [michaelworm/grunt-inky#1]
Hi,
I'm getting this message on inky task when making a new install:
`Warning: convertedHtml.html is not a function`

After some investigation there's a new version of inky that seems to break your plugin. 
Adding the 1.3.5 (strict) inky version to the project dependencies resolves the error.

Thanks for this plugin and for thinking about grunt users.

**Comment by michael-jahn-dev** [comment]
Hey @alekart thanks for the report!

It seems that this commit is causing the issue: https://github.com/zurb/inky/pull/57/commits/5f4cb497445ff69714192d6cae5d417c94de1b26
