### ISSUE TITLE
Unicode characters do not covert correctly

### ISSUE THREAD

**Issue by matmiz** [michaelworm/grunt-inky#4]
Hey,
Great tool, it helped me a lot, thanks! 
I have an issue, and i'm not sure whether it is in here, or in F4E.
When i'm using unicode characters, it does not compile correctly:
This is the code:
![screen shot 2016-12-25 at 18 25 32](https://cloud.githubusercontent.com/assets/1095554/21472029/02f3a66c-cad0-11e6-848c-819aee9c38a3.png)

This is how the emails looks like:
![screen shot 2016-12-25 at 18 27 26](https://cloud.githubusercontent.com/assets/1095554/21472028/02f3383a-cad0-11e6-9f2d-7bc4c77a9e6d.png)

This happens for all email clients.

**Comment by michael-jahn-dev** [comment]
Hey thanks for the support!

This issue seems to be related to Inky itself since this is just the grunt
task which relies on Inky. Could you open an issue over there?

Greetings and merry xmas,
Miw0

Am 25.12.2016 5:30 nachm. schrieb "Matan Mizrahi" <notifications@github.com
